name: Run tests and linters
on:
  push:
jobs:
  Run-tests-and-linter:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: task_manager
        ports:
          5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Composer install
        run: composer install

      - name: Create file .env
        run: cp -p .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Migrate tables
        run: php artisan migrate

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint

      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true
