name: Run tests and linters
on:
  push:
jobs:
  Run-tests-and-linter:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: task_manager
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install application
        run: make install

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint
